name: Ameba LS

on:
  push:
    paths:
      - "**/*.cr"
  pull_request:
    branches: [main]
    paths:
      - "**/*.cr"

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crystal: [latest, nightly]

    steps:
      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: shards install

      - name: Build Ameba LS binary
        run: shards build ameba-ls

      - name: Run Ameba Linter
        run: bin/ameba
